---
- name: Installer Apache2 sur les hôtes
  hosts: all
  become: yes
  tasks:
    - name: Mettre à jour la liste des packages
      apt:
        update_cache: yes

    - name: Installer Apache2
      apt:
        name: apache2
        state: present

    - name: S'assurer qu'Apache est démarré et activé
      service:
        name: apache2
        state: started
        enabled: yes
